server:
  port: 0

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: true
        errorDecoder: com.basalt.echo.upper.FeignErrorDecoder

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    export:
      prometheus:
        enabled: true

echo:
  value: value from application.yml
